# Generated by Django 5.2.1 on 2026-01-26 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_options_alter_systemsetting_options_and_more'),
        ('students', '0002_enrollment_enrolled_at_alter_enrollment_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'انتخاب واحد', 'verbose_name_plural': 'لیست انتخاب واحد'},
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to='courses.course', verbose_name='درس'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrolled_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت\u200cنام'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='is_passed',
            field=models.BooleanField(default=False, verbose_name='پاس شده'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='دانشجو'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='term',
            field=models.CharField(default='1402-2', max_length=10, verbose_name='ترم'),
        ),
    ]
