# Generated by Django 5.2.1 on 2026-01-26 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_capacity_alter_course_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'درس', 'verbose_name_plural': 'دروس'},
        ),
        migrations.AlterModelOptions(
            name='systemsetting',
            options={'verbose_name': 'تنظیمات سیستم', 'verbose_name_plural': 'تنظیمات سیستم'},
        ),
        migrations.AlterField(
            model_name='course',
            name='capacity',
            field=models.IntegerField(verbose_name='ظرفیت'),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='کد درس'),
        ),
        migrations.AlterField(
            model_name='course',
            name='day',
            field=models.CharField(max_length=20, verbose_name='روز برگزاری'),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_time',
            field=models.TimeField(verbose_name='زمان پایان'),
        ),
        migrations.AlterField(
            model_name='course',
            name='location',
            field=models.CharField(max_length=100, verbose_name='مکان برگزاری'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام درس'),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, to='courses.course', verbose_name='پیش\u200cنیازها'),
        ),
        migrations.AlterField(
            model_name='course',
            name='professor',
            field=models.ForeignKey(limit_choices_to={'is_professor': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='استاد'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_time',
            field=models.TimeField(verbose_name='زمان شروع'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='max_units',
            field=models.PositiveIntegerField(default=20, verbose_name='حداکثر واحد'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='min_units',
            field=models.PositiveIntegerField(default=12, verbose_name='حداقل واحد'),
        ),
    ]
