# Generated by Django 5.2.1 on 2026-01-27 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_options_alter_systemsetting_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='day',
            field=models.CharField(choices=[('1', 'شنبه'), ('2', 'یکشنبه'), ('3', 'دوشنبه'), ('4', 'سه\u200cشنبه'), ('5', 'چهارشنبه'), ('6', 'پنج\u200cشنبه'), ('7', 'جمعه')], default='1', max_length=1, verbose_name='روز برگزاری'),
        ),
    ]
